### PR TITLE
Random voxel filtering.

### PR DESCRIPTION
**Pull request by wohe**
This leads to slightly slower performance but better quality.
Also replaces the VoxelFilter class by free standing functions.

Signed-off-by: Wolfgang Hess <whess@lyft.com>

### CODE REVIEW

**Comment by bochen87** [comment]
When you say "slightly", did you do some tests? can you express in CPU usage?

**Comment by wohe** [comment]
@bochen87 Yes, of course. Main point here is better quality. Exact performance numbers depend on the sensors used and the environment. For the 3D backpack example voxel filtering takes a few milliseconds and performance regression is a fraction of that.

**Comment by bochen87** [comment]
Ok, cool!

**Comment by wohe** [comment]
Thanks for the review. Some numbers from the 3D demo:
CPU time changes from 1037 s to 1068 s (+3%)
712 loop closures are found instead of 681 (+5%)
translational residuals are 4.5 cm mean instead of 4.9 cm mean (-8%)
rotational residuals are 7.6 mrad means instead of 7.8 mrad (-3%)

**Comment by bochen87** [comment]
thanks for also posting some numbers, very insightful! :+1:

**Pull request merged**
