### PR TITLE
Change from Google CLA to DCO in CONTRIBUTING.md.

### PR DESCRIPTION
**Pull request by wohe**

### CODE REVIEW

**Comment by wohe** [comment]
FYI @kscottz

**Comment by wohe** [comment]
@dirk-thomas Hi, I saw you did the DCO changes in the ros2 repos. Does this look good to you? Background of this change is that this project now belongs to Open Robotics.

**Comment by dirk-thomas** [comment]
Looks ok to me.

**Comment by danielsievers** [comment]
👍

**Pull request merged**
