### PR TITLE
Use FetchContent to download and configure Abseil at configure time

### PR DESCRIPTION
**Pull request by ojura**
I stumbled across a cool CMake module called `FetchContent`:
https://cmake.org/cmake/help/git-stage/module/FetchContent.html

It is very similar to `ExternalProject`, but it handles downloading dependencies at CMake configure time. Thus we can `add_subdirectory()` Abseil [just like the official documentation recommends](https://github.com/abseil/abseil-cpp/blob/master/CMake/README.md). CMake then knows about all Abseil targets and how they depend on each other since they're built in the same project, and we can link against them in a sane manner without having to enumerate all those static libraries in the right order. This also works much better with multi-configuration build systems such as MSVC since we properly propagate the build type.

The only downside is that this module was introduced very recently, in CMake 3.11. However, it's trivial to backport it to older CMake versions by just providing a copy, which I did in this PR.

@pifon2a

### CODE REVIEW

**Comment by ojura** [comment]
@pifon2a WDYT?

**Comment by MichaelGrupp** [comment]
@ojura  @pifon2a This looks like an useful addition, any updates on this? Besides removing the warnings, I think you need to declare the dependency for the flat hash maps that were added recently to make it compile without errors.

**Comment by pifon2a** [comment]
@MichaelGrupp yep, https://github.com/Mizux/abseil-cpp/commit/f18b05de3a148c4c1c8d46703ad13f33e7c76cfd

**Comment by ojura** [comment]
@MichaelGrupp thanks for the hint. I added linking against `absl::hash` and it builds. But it looks like that @pifon2a is waiting for Abseil to become installable :)

**Comment by wohe** [comment]
Closing in favor of #1570.

**Comment by ojura** [comment]
@wohe if we’re not providing support for building abseil in Cartographer, we will require installing it as a dependency?

**Comment by wohe** [comment]
@ojura The change leaves it to the user to decide how they want to satisfy the dependency. You can for example use stow and run the script. Another possibility with ROS is to add a catkin-aware version of Abseil and let catkin build it.

**Pull request closed without merging**
