### PR TITLE
Stop using broken async_grpc::Client retry strategy

### PR DESCRIPTION
**Pull request by cschuet**

### CODE REVIEW

**Comment by cschuet** [comment]
@MichaelGrupp FYI

**Comment by MichaelGrupp** [comment]
Please wait.

We should try using https://github.com/grpc/grpc/blob/master/doc/keepalive.md

**Comment by pifon2a** [comment]
@cschuet , @MichaelGrupp is this PR still relevant?

**Comment by MichaelGrupp** [comment]
This was and is a hack to catch physical network outage, which is not always caught in the gRPC channel state. The `async_grpc` retry strategies didn't work well in this situation, so we did a workaround that recreates the client periodically (reconnecting every time, catching bad connections).

As I wrote in my previous comment, a heartbeat/keepalive for the channel is probably a cleaner way to go. Also, a channel state notification (as discussed internally, see my mail: "If you are not sending RPCs and not subscribed for channel state notifications, you might not see the channel going disconnected.")

**Comment by MichaelGrupp** [comment]
I think we can close this, but should continue tracking it in an issue.

I can open one.

**Pull request closed without merging**
